### PR TITLE
Update GbDoc according to full schema

### PR DESCRIPTION
**Pull request by ronaldtse**
Changes according to official GB schema.

Sources:
- "Management of National Standards" by the "General Administration of Quality Supervision, Inspection and Quarantine." ("ASQIQ") ("国家标准管理办法":  http://www.aqsiq.gov.cn/xxgk_13386/zvfg/flfg/201704/P020170407633109310632.pdf) 
- Standards Administration of China search engine: http://std.sacinfo.org.cn

Model changes:

- Simplified according to latest StanDoc and IsoDoc changes to preface.

- Adds `planNumber` as attribute of `GbDoc`
  - Plan number registered at the General Administration of Quality Supervision, Inspection and Quarantine. 计划项目编号, 国家技术监督局的国家标准制定计划中的项目编号。
  - (extracted from `LibraryIds`)

- `ccs` is now an attribute of `GbDoc`, and its modeling also added
  
  - field (single character, like "L")
  - group (string, like "L10/34")
  - subgroup (integer, like "30")

- Added `GbStandardType` enumeration for StandardType (from official AQSIQ form)

  - basic
  - health_and_safety
  - environment_protection
  - engineering_and_construction
  - product
  - method
  - management_techniques
  - others

- Adoption from international standards is achieved using `BibliographicItem.relations` which also takes the international standard's `BibItem`:
  - identical (等同采用)
  - equivalent (等效采用)
  - nonequivalent (参照采用)

- StandardState is modeled using `BibliographicDate`:
  - activated (Current, 现行)
  - published (Pending activation, 即将实施)
  - obsoleted (Revoked, 废止)

### CODE REVIEW

**Comment by ronaldtse** [comment]
This answers most of the questions in #6 except the contributors.

**Comment by opoudjis** [comment]
CCS: 

They are much simpler than the grammar says

in A42

A is the field, 4 is the group, and 2 is the subgroup

the group has the artificial name E00/09

which simply means the range from E00 to E09

but in practice, there is no need at all to break this down into field, group, and subgroup

in the xml

it's just a single code

and something else (like your new gem) should be breaking it down into its three components

**Comment by opoudjis** [comment]
GB standard type: for consistency with ISOdoc, these are hyphenated.

There is no Standard Type in the ISO grammar. There is the Document Type, but that divides standards into specifications, reports, guide, etc; this Standard Type is rather a thematic classification, and it is not the same kind of thing, nor should it inherit from the ISO Standard Type. 

You now dangerously have a GbStandardType container and a GbStandardType attribute. I am renaming the latter StandardTopic, and making it an attribute of GbStandardType.

**Comment by ronaldtse** [comment]
Re: CCS.

There is a reason why I've left it as that, and the reason is that they really use it that way -- there is a specific description that applies to the E00/09 group (see cn-ccs-codes/cat-level2.csv) that is distinct from the E00 to E09 descriptions.
 
You are right that there is no need to deal with those components in the XML.

Just like how in ICS XX.YY.ZZ is the code, but we don't need to separate XX, YY and ZZ.

**Comment by ronaldtse** [comment]
Re: GbStandardType

Mistake on my part -- didn't realized we already used the same name, so I've adjusted according to your description -- it's now GbStandardTopic, but it is an attribute of GbBibItem not GbStandardType.

**Pull request merged**
